# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

MAJ <- function(Q0, chd, NN) {
    .Call(`_modelaj_MAJ`, Q0, chd, NN)
}

rcpp_hello_world <- function() {
    .Call(`_modelaj_rcpp_hello_world`)
}

