# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

M2HT <- function(Q0, chd, NN) {
    .Call(`_model2ht_M2HT`, Q0, chd, NN)
}

rcpp_hello_world <- function() {
    .Call(`_model2ht_rcpp_hello_world`)
}

