// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// MAJ
double MAJ(NumericVector Q0, NumericVector chd, NumericVector NN);
RcppExport SEXP _modelaj_MAJ(SEXP Q0SEXP, SEXP chdSEXP, SEXP NNSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type Q0(Q0SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type chd(chdSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type NN(NNSEXP);
    rcpp_result_gen = Rcpp::wrap(MAJ(Q0, chd, NN));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP _modelaj_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello_world());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_modelaj_MAJ", (DL_FUNC) &_modelaj_MAJ, 3},
    {"_modelaj_rcpp_hello_world", (DL_FUNC) &_modelaj_rcpp_hello_world, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_modelaj(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
